django:
    image: django-docker
    ports:
        - "8000:8000"
    volumes:
        - ./app:/var/www/html
        - ./eventex-entrypoint:/usr/local/bin/eventex-entrypoint
    entrypoint: /usr/local/bin/eventex-entrypoint
